name: C-extension-task
on: 
  push:

jobs:
  unix:
    name: ${{ matrix.os }} ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python: [3.5.4, 3.5.9, 3.6.7, 3.6.8, 3.6.9, 3.6.10, 3.7.5, 3.7.6, 3.7.7, 3.8.0, 3.8.1, 3.8.2]
    steps:
    - run: echo '::set-env name=RUNNER_TOOL_CACHE::/opt/hostedtoolcache'
    - run: echo '::set-env name=AGENT_TOOLSDIRECTORY::/opt/hostedtoolcache'
    - run: mkdir -p $RUNNER_TOOL_CACHE
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup python 
      uses: ./
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
      working-directory: 'applications/c-extension/'

    - name: Make
      run: make
      working-directory: 'applications/c-extension/'
      shell: pwsh

  unix2:
    name: ${{ matrix.os }} ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-16.04, ubuntu-18.04]
        python: [3.5.4, 3.5.9, 3.6.7, 3.6.8, 3.6.9, 3.6.10, 3.7.5, 3.7.6, 3.7.7, 3.8.0, 3.8.1, 3.8.2]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup python 
      uses: ./
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
      working-directory: 'applications/c-extension/'

    - name: Make
      run: make
      working-directory: 'applications/c-extension/'
      shell: pwsh

