name: C-extension
on: 
  push:

jobs:
  default-version:
    name: Setup default version
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-18.04]
        python: [3.5.3, 3.5.4, 3.6.6, 3.6.8, 3.7.4, 3.7.6, 3.8.1, 3.8.2]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup default python 
      uses: ./
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
      working-directory: 'applications/c-extension/'

    - name: Make
      run: make
      working-directory: 'applications/c-extension/'
      shell: pwsh
