name: C-extension
on: 
  push:

jobs:
  unix:
    name: NPM install
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: New step
      run: |
        wget https://github.com/maxim-lobanov/setup-python/releases/download/7.0/toolcache-python-ubuntu-1804-x64-3.8.11581679880-npm.tgz -O "install.tgz" > /dev/null
        mkdir install
        tar zxvf "install.tgz" -C install
        ls install
        echo "----"
        ls install/package

        cd install/package
        chmod +x ./setup.sh
        ./setup.sh

    - name: Debug
      run: |
        python --version
        which python
        ls /opt/hostedtoolcache/Python

    - name: setup default python 
      uses: ./
      with:
        python-version: 3.8.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
      working-directory: 'applications/c-extension/'

    - name: Make
      run: make
      working-directory: 'applications/c-extension/'
      shell: pwsh

    # name: ${{ matrix.os }} ${{ matrix.python }}
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     # os: [macos-latest, ubuntu-16.04, ubuntu-18.04]
    #     os: [ubuntu-16.04, ubuntu-18.04]
    #     python: [3.5.3, 3.5.4, 3.6.6, 3.6.8, 3.7.4, 3.7.6, 3.8.1, 3.8.2]
    #     # python: [3.5.9, 3.6.10, 3.7.6, 3.8.2]
    # steps:
    # - name: Checkout
    #   uses: actions/checkout@v2


    # - name: New step
    #   run: |
    #     sudo chown $USER:runneradmin -R /opt/hostedtoolcache/Python

  
  # win:
  #   name: Windows ${{ matrix.python }}
  #   runs-on: 'windows-latest'
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python: [3.6.6, 3.6.8, 3.7.4, 3.7.6, 3.8.1, 3.8.2]
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: setup default python 
  #     uses: ./
  #     with:
  #       python-version: ${{ matrix.python }}

  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install wheel
  #     working-directory: 'applications/c-extension/'

  #   - name: Make
  #     run: make
  #     working-directory: 'applications/c-extension/'
  #     shell: pwsh
