name: C-extension
on: 
  push:

jobs:
  unix_npm:
    name: NPM install
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: New step
      run: |
        wget https://github.com/maxim-lobanov/setup-python/releases/download/7.0/toolcache-python-ubuntu-1804-x64-3.6.101581681022-npm.tgz -O "install.tgz" > /dev/null
        mkdir install
        tar zxvf "install.tgz" -C install
        ls install
        echo "----"
        ls install/package

        cd install/package
        chmod +x ./setup.sh
        ./setup.sh

    - name: setup default python 
      uses: ./
      with:
        python-version: 3.6.10

    - name: Debug
      run: |
        python --version
        which python
        ls /opt/hostedtoolcache/Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
      working-directory: 'applications/c-extension/'

    - name: Make
      run: make
      working-directory: 'applications/c-extension/'
      shell: pwsh

  unix_github:
    name: GitHub install
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: New step
      run: |
        wget https://github.com/actions/python-versions/releases/download/3.6.10-20200424.78/python-3.6.10-ubuntu-1804-x64.tar.gz -O "install.tgz" > /dev/null
        mkdir install
        tar zxvf "install.tgz" -C install
        ls install
        echo "----"
        ls install/package

        cd install/package
        chmod +x ./setup.sh
        ./setup.sh

    - name: setup default python 
      uses: ./
      with:
        python-version: 3.6.10

    - name: Debug
      run: |
        python --version
        which python
        ls /opt/hostedtoolcache/Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
      working-directory: 'applications/c-extension/'

    - name: Make
      run: make
      working-directory: 'applications/c-extension/'
      shell: pwsh