name: Validate 'setup-python'
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created, deleted]

jobs:
  default-version:
    name: Setup latest version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-18.04]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python default
      uses: ./

    - name: Validate version
      run: python --version

  all-available-versions:
    name: Setup all available versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-18.04]
        python: [2.7.17, 3.5.4, 3.5.9, 3.6.8, 3.6.10, 3.7.6, 3.8.2]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python ${{ matrix.python }}
      uses: ./
      if: matrix.python == 3.5.9
      with:
        python-version: ${{ matrix.python }}

    - name: Validate version
      run: python --version

  setup-on-clean-machine:
    name: Setup version on clean machine (2.7.17)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-16.04, ubuntu-18.04]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Clean machine
      run: |
        if ("${{ matrix.os }}" -eq "windows-latest") {
          $PythonFilter = "Name like '%Python%'"
          Get-WmiObject Win32_Product -Filter $PythonFilter | Foreach-Object { 
              Write-Host "Uninstalling $($_.Name) ..."
              $_.Uninstall() | Out-Null 
          }
        }
        Remove-Item -Path "${env:AGENT_TOOLSDIRECTORY}/Python" -Recurse -Force
      shell: pwsh

    - name: setup-python 2.7.17
      uses: ./
      with:
        python-version: 2.7.17

    - name: Validate version
      run: python --version