name: Validate 'setup-python'
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created, deleted]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python
      uses: ./
      with:
        python-version: 3.8.2

    - name: Validate version
      run: python --version