name: Validate 'setup-python'
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created, deleted]

jobs:
  powershell-version:
    name: Setup latest version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-18.04]
    steps:
    - name: Validate version
      run: $PSVersionTable.PSVersion
      shell: powershell

  default-version:
    name: Setup latest version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python default
      uses: ./

    - name: Validate version
      run: python --version

  pre-installed-version:
    name: Setup pre-installed version (3.7.6)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python 3.7.6
      uses: ./
      with:
        python-version: 3.7.6

    - name: Validate version
      run: python --version

  version-from-releases:
    name: Setup version from releases (3.6.8)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python 3.6.8
      uses: ./
      with:
        python-version: 3.6.8

    - name: Validate version
      run: python --version

  setup-on-clean-machine:
    name: Setup version on clean machine (2.7.17)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Clean machine
      run: |
        if ("${{ matrix.os }}" -eq "windows-latest") {
          $PythonFilter = "Name like '%Python%'"
          Get-WmiObject Win32_Product -Filter $PythonFilter | Foreach-Object { 
              Write-Host "Uninstalling $($_.Name) ..."
              $_.Uninstall() | Out-Null 
          }
        }
        Remove-Item -Path "${env:AGENT_TOOLSDIRECTORY}/python" -Recurse -Force
      shell: powershell

    - name: setup-python 2.7.17
      uses: ./
      with:
        python-version: 2.7.17

    - name: Validate version
      run: python --version