name: Validate 'setup-python'
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created, deleted]

jobs:
  Macos:
    name: Macos
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python '2.x'
      uses: ./
      with:
        python-version: '2.x'

    - name: Validate version
      run: python --version

    - name: setup-python 3.6.8
      uses: ./
      with:
        python-version: 3.6.8

    - name: Validate version
      run: python --version

    - name: setup-python 3.8.2
      uses: ./
      with:
        python-version: 3.8.2

    - name: Validate version
      run: python --version
    
    - name: setup-python 3.9.2
      uses: ./
      with:
        python-version: 3.9.2

    - name: Validate version
      run: python --version

  Ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python '2.x'
      uses: ./
      with:
        python-version: '2.x'

    - name: Validate version
      run: python --version

    - name: setup-python 3.6.8
      uses: ./
      with:
        python-version: 3.6.8

    - name: Validate version
      run: python --version

    - name: setup-python 3.8.2
      uses: ./
      with:
        python-version: 3.8.2

    - name: Validate version
      run: python --version
    
    - name: setup-python 3.9.2
      uses: ./
      with:
        python-version: 3.9.2

    - name: Validate version
      run: python --version