name: Validate 'setup-python'
on: 
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  setup-versions-from-manifest:
    name: Setup versions available only from the manifest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-18.04]
        python: [3.5.4, 3.6.8, 3.7.4, 3.7.5]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python ${{ matrix.python }}
      uses: ./
      if: "!( matrix.os == 'windows-latest' && (matrix.python == '3.5.4' || matrix.python == '3.6.8') )"
      with:
        python-version: ${{ matrix.python }}

    - name: Validate version
      run: python --version

    - name: Run simple python code
      run: python __tests__/simple_test.py
