name: Validate 'setup-python'
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created, deleted]

jobs:
  Macos:
    name: Macos. Setup latest version
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python default
      uses: ./

    - name: Validate version
      run: python --version

  Macos:
    name: Macos. Setup pre-installed version (3.7.6)
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python 3.7.6
      uses: ./
      with:
        python-version: 3.7.6

    - name: Validate version
      run: python --version

  Macos:
    name: Macos. Setup version from releases (3.6.8)
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python 3.6.8
      uses: ./
      with:
        python-version: 3.6.8

    - name: Validate version
      run: python --version

  Macos:
    name: Macos. Setup version on clean machine (2.7.17)
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Clean machine
      run: Remove-Item -Path "${env:AGENT_TOOLSDIRECTORY}/python" -Recurse -Force
      shell: powershell

    - name: setup-python 2.7.17
      uses: ./
      with:
        python-version: 2.7.17

    - name: Validate version
      run: python --version